{% set name = "jupyterlab-kernelspy" %}
{% set version = "4.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_kernelspy-{{ version }}.tar.gz
  sha256: f36ed0f1adf0adfa99ff30eaa88e4fcef645c6822588eefb8c0bb08a18929aa0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatch-jupyter-builder >=0.8.1
    - hatchling
    - jupyterlab >=4,<5
    - jupyter-packaging >=0.10.0,<2.0.0
  run:
    - python >=3.7
  run_constrained:
    - jupyterlab >=4,<5

test:
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/jupyterlab-kernelspy/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-kernelspy\\package.json (exit 0) else (exit 1)          # [win]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-kernelspy
  summary: A JupyterLab extension for inspecting messages to/from a kernel
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - fcollonval
    - jtpio
    - martinRenou
