{% set name = "jupyterlab-kernelspy" %}
{% set version = "3.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5c4439e08aae27d0ccff3697603d5ae97558dc7e2626247f22abe1fc6ec13e90

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - jupyterlab >=3.1,<4
    - jupyter-packaging >=0.10.0,<2.0.0
  run:
    - python >=3.7

test:
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/jupyterlab-kernelspy/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\jupyterlab-kernelspy\\package.json (exit 0) else (exit 1)          # [win]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-kernelspy
  summary: A JupyterLab extension for inspecting messages to/from a kernel
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - fcollonval
    - jtpio
